/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Success
 */
export type CreateUserResponseBody = {
  json: components.User;
};

/** @internal */
export const CreateUserResponseBody$inboundSchema: z.ZodType<
  CreateUserResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  json: components.User$inboundSchema,
});

/** @internal */
export type CreateUserResponseBody$Outbound = {
  json: components.User$Outbound;
};

/** @internal */
export const CreateUserResponseBody$outboundSchema: z.ZodType<
  CreateUserResponseBody$Outbound,
  z.ZodTypeDef,
  CreateUserResponseBody
> = z.object({
  json: components.User$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateUserResponseBody$ {
  /** @deprecated use `CreateUserResponseBody$inboundSchema` instead. */
  export const inboundSchema = CreateUserResponseBody$inboundSchema;
  /** @deprecated use `CreateUserResponseBody$outboundSchema` instead. */
  export const outboundSchema = CreateUserResponseBody$outboundSchema;
  /** @deprecated use `CreateUserResponseBody$Outbound` instead. */
  export type Outbound = CreateUserResponseBody$Outbound;
}

export function createUserResponseBodyToJSON(
  createUserResponseBody: CreateUserResponseBody,
): string {
  return JSON.stringify(
    CreateUserResponseBody$outboundSchema.parse(createUserResponseBody),
  );
}

export function createUserResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateUserResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateUserResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateUserResponseBody' from JSON`,
  );
}
