"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user import User, UserTypedDict
from openapi.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class CreateUserResponseBodyTypedDict(TypedDict):
    r"""Success"""

    json_: UserTypedDict


class CreateUserResponseBody(BaseModel):
    r"""Success"""

    json_: Annotated[User, pydantic.Field(alias="json")]
