"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from openapi.types import BaseModel
from typing import Literal, Optional
from typing_extensions import NotRequired, TypedDict


class AddressTypedDict(TypedDict):
    street: NotRequired[str]
    city: NotRequired[str]
    state: NotRequired[str]
    zip: NotRequired[str]


class Address(BaseModel):
    street: Optional[str] = None

    city: Optional[str] = None

    state: Optional[str] = None

    zip: Optional[str] = None


Gender = Literal["MALE", "FEMALE", "OTHER"]


class UserTypedDict(TypedDict):
    id: str
    name: str
    address: AddressTypedDict
    age: int
    gender: Gender


class User(BaseModel):
    id: str

    name: str

    address: Address

    age: int

    gender: Gender
