// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type CreateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	User *components.User
}

func (o *CreateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateUserResponse) GetUser() *components.User {
	if o == nil {
		return nil
	}
	return o.User
}
