// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

// CreateUserResponseBody - Success
type CreateUserResponseBody struct {
	JSON components.User `json:"json"`
}

func (o *CreateUserResponseBody) GetJSON() components.User {
	if o == nil {
		return components.User{}
	}
	return o.JSON
}

type CreateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Success
	Object *CreateUserResponseBody
}

func (o *CreateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *CreateUserResponse) GetObject() *CreateUserResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
