// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"openapi/models/components"
)

type UpdateUserRequest struct {
	ID   string          `pathParam:"style=simple,explode=false,name=id"`
	User components.User `request:"mediaType=application/json"`
}

func (o *UpdateUserRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *UpdateUserRequest) GetUser() components.User {
	if o == nil {
		return components.User{}
	}
	return o.User
}

type UpdateUserResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	User *components.User
}

func (o *UpdateUserResponse) GetHTTPMeta() components.HTTPMetadata {
	if o == nil {
		return components.HTTPMetadata{}
	}
	return o.HTTPMeta
}

func (o *UpdateUserResponse) GetUser() *components.User {
	if o == nil {
		return nil
	}
	return o.User
}
