workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    testgendemo:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/testgendemo
targets:
    go:
        target: go
        source: testgendemo
        output: ./go
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/testgendemo-go-code-samples
            blocking: false
        # testing:
        #     enabled: true
    python:
        target: python
        source: testgendemo
        output: ./python
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/testgendemo-python-code-samples
            blocking: false
        # testing:
        #     enabled: true
    typescript:
        target: typescript
        source: testgendemo
        output: ./typescript
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/testgendemo-typescript-code-samples
            blocking: false
        # testing:
        #     enabled: true
